issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: '_test\.go'
      linters:
        - bodyclose
        - gocognit
        - goconst
        - gocyclo
        - gosec
        - lll
        - prealloc

    # Duplicates of errcheck
    - linters: [gosec]
      text: 'G104: Errors unhandled'
    - linters: [gosec]
      text: 'G307: Deferring unsafe method'

    # Contexts are best assigned defensively
    - linters: [ineffassign]
      text: 'ineffectual assignment to ctx'
    - linters: [staticcheck]
      text: 'SA4006: this value of `ctx` is never used'

    # we dont care about package comments
    - linters: [stylecheck]
      text: 'ST1000: at least one file in a package should have a package comment'

linters:
  enable:
    - bodyclose
    - errcheck
    - errchkjson
    - exportloopref
    - goconst
    - gocognit
    - gocyclo
    - godot
    - gofumpt
    - goimports
    - gosec
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - stylecheck

linters-settings:
  errcheck:
    exclude-functions:
      # Errors we wouldn't act on after checking
      - (*database/sql.DB).Close
      - (*database/sql.Rows).Close
      - (io.Closer).Close
      - (*os.File).Close
      - (net/http.ResponseWriter).Write

      # Handled by errchkjson
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
      - (*encoding/json.Encoder).Encode

  gocognit:
    min-complexity: 10

  goconst:
    min-len: 0
    min-occurrences: 3

  gocyclo:
    min-complexity: 10

  goimports:
    local-prefixes: github.com/morningconsult/serrors

  govet:
    check-shadowing: true

  nakedret:
    max-func-lines: 0

  revive:
    confidence: 0
    rules:
      - name: exported
        disabled: false
        severity: warning
      - name: unused-parameter
        disabled: false
        severity: warning
