issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: '_test\.go'
      linters:
        - bodyclose
        - gocognit
        - gocyclo
        - gosec
        - lll
        - prealloc

    # Duplicates of errcheck
    - linters: [gosec]
      text: 'G104: Errors unhandled'
    - linters: [gosec]
      text: 'G307: Deferring unsafe method'

linters:
  enable:
    - bodyclose
    - errcheck
    - errchkjson
    - exptostd
    - fatcontext
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gofumpt
    - goimports
    - gosec
    - lll
    - misspell
    - nakedret
    - nilnesserr
    - nolintlint
    - perfsprint
    - prealloc
    - revive
    - sloglint
    - unconvert
    - unparam
    - usetesting

linters-settings:
  errcheck:
    exclude-functions:
      # Handled by errchkjson
      - encoding/json.Marshal
      - encoding/json.MarshalIndent
      - (*encoding/json.Encoder).Encode

  gocognit:
    min-complexity: 10

  gocyclo:
    min-complexity: 10

  goimports:
    local-prefixes: github.com/morningconsult/serrors

  govet:
    enable:
      - shadow

  nakedret:
    max-func-lines: 0

  revive:
    confidence: 0

  sloglint:
    args-on-sep-lines: true
