name: Test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - '1.23'
          - '1.24'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - uses: actions/checkout@v4
      - run: go test ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.2
